version: 2


models:
  - name: enriched_trial
    description: This table has all information about a session.

    columns:
      - name: session_id
        description: This is a unique identifier for a session.
        tests:
          - not_null