version: 2


models:
  - name: curated_time
    description: This table has all information about a date/time (down to hour) of use.

    columns:
      - name: time_id
        description: This is a unique identifier for an hour.
        tests:
          - unique
          - not_null