# Configuration valeus

[runtime]
log_level="WARNING"  
dlthub_telemetry = true

[sources.google_sheets]
spreadsheet_url_or_id = "19TOJJeAPXJN-WyepIF93naUPXTQw6PjlkHW627UXR1g"
range_names = ["Device"]