version: 2

sources:
  - name: warehouse  
    database: "{{ env_var('DATABRICKS_PROJECT_ENV', 'dev') }}"
    schema: processed 
    tables:
      - name: stg_eaton_combined
      - name: fact_stg_nodes
      - name: files
      - name: device
      - name: session
      - name: facility
      - name: time
      - name: user
      - name: week
    schema: integrated 
    tables:
      - name: stg_nodes
    schema: integrated
    tables:
      - name: physical_therapy_evals
      - name: user_surveys
