version: 2


models:
  - name: enriched_hour
    description: This table has all information about a date/time of use.

    columns:
      - name: time_id
        description: This is a unique identifier for an hour.
        tests:
          - not_null