version: 2

sources:
  - name: dev_wh  
    database: dev
    schema: integrated 
    tables:
      - name: stg_nodes
      - name: physical_therapy_evals
      - name: user_surveys
      - name: files
